--- 

- hosts: localhost
  remote_user: vagrant
  connection: local

  tasks:
    - name: get system date
      get_current_date:
      register: dt
      tags:
        - date
        - t2

    - name: print date
      debug: msg={{ dt.date }}
      tags:
        - t2
