--- 

- hosts: localhost
  remote_user: vagrant
  connection: local
 
  tasks:
#    - name: curl command
#      shell: "curlfile.sh"
    - name: using touch
      command: /usr/bin/touch /Users/supriyasubudhi/vagrant_getting_started/hi.txt

    - name: curl command
      command: /usr/bin/curl google.com
      register: msg1

    - name: display
      debug: msg="{{ msg1 }}"

